openapi: 3.0.0
info:
  description: "Swagger proposed server for the Review Product infrastructure at ACME .Inc"
  version: "0.1"
  title: "ACME Reviews - PSIDI"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "1171071@isep.ipp.pt"
    
servers:
  - url: https://psidi-customers.herokuapp.com/v1
    description: Profile server   
  - url: https://reviews-psidi.herokuapp.com/
    description: Evaluation server 
  - url: https://catalog-psidi.herokuapp.com/v1
    description: Catalog server 
    
tags:
- name: "customers"
  description: "Handles the Profile service requests"
- name: "products"
  description: "Handles the Catalog service requests"
- name: "reviews"
  description: "Handles the Evaluation service requests"

paths:

####### Customer ########

  /customers:
    post:
      tags:
      - "customers"
      summary: "Register a New Customer"
      description: ""
      operationId: "registerCustomer"
      requestBody:
        required: true
        description: "The data used to create a customer (name, username, password, etc)"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
          application/xml:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '201':
          description: "Customer Registered"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  customerId:
                    type: "string"
                    default: "https://psidi-customers.herokuapp.com/v1/customers/:id"
            application/xml:
              schema:
                type: "object"
                xml: 
                  name: "customer"
                properties:
                  customerId:
                    type: "integer"
                    format: "int64"
                    description: "ID of the created user"
          links:
            GetCustomerById: 
              operationId: getCustomer
              parameters:
                customerId: '$response.body#/customerId'
                required: true
                description: ""
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      deprecated: false  
      
  /customers/{customerId}:
    get:
      tags:
      - "customers"
      summary: "Get a Customer By Id"
      description: ""
      operationId: "getCustomer"
      parameters:
        - in: "path"
          name: "customerId"
          required: true  
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Customer Obtained"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
            application/xml:
              schema:
                $ref: "#/components/schemas/Customer"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      security:
        - OAuth2: [customer_read]
      deprecated: false  

####### Products #######

  /products:
    get:
      tags:
      - "products"  
      summary: "Returns all of the Products list from the Catalog, where each product includes the description of name and barcode"
      description: ""
      operationId: "getProducts"
      parameters:
        - in: "query"
          name: "Product Name"
          required: false  
          schema:
            type: string
        - in: "query"
          name: "Barcode"
          required: false  
          schema:
            type: string
      responses:
        '200':
          description: "Products Fetched. Returns a Pagination Object, which contains a list with productIds"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Pagination"
            application/xml:
               schema:
                  $ref: "#/components/schemas/Pagination"
          links:
            GetProductsById: 
              operationId: getProduct
              parameters:
                productId: '$response.body#/products/productId'
                required: true
                description: ""
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"
      deprecated: false  

  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Get a Product By Id"
      description: "Returns a certain product according to an id that the API user inserts"
      operationId: "getProduct"
      parameters:
        - in: "path"
          name: "productId"
          required: true  
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Product Obtained"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Product"
            application/xml:
               schema:
                  $ref: "#/components/schemas/Product"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      deprecated: false  
      
   
####### Reviews ########

  /reviews/{reviewId}:
    patch:
      tags:
      - "reviews"  
      summary: "Update a Review Status"
      description: ""
      operationId: "updateReviewsStatus"
      requestBody:
        required: true
        description: "The data used to update a review (status)"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Review-Status"
          application/xml:
            schema:
              $ref: "#/components/schemas/Review-Status"
      parameters:
        - in: "path"
          name: "reviewId"
          required: true  
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "Review Updated"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  reviewId:
                    default: "https://reviews-psidi.herokuapp.com/reviews/:id"
            application/xml:
              schema:
                type: "object"
                xml: 
                  name: "review"
                properties:
                  reviewId:
                    type: "integer"
                    format: "int64"
                    description: "ID of the updated review"
          links:
            GetReviewById: 
              operationId: getReview
              parameters:
                customerId: '$response.body#/reviewId'
                required: true
                description: ""
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      security:
        - OAuth2: [moderator]
    get:
      tags:
      - "reviews"
      summary: "Get a Review By Id"
      description: ""
      operationId: "getReview"
      parameters:
        - in: "path"
          name: "reviewId"
          required: true  
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Review Obtained"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"
            application/xml:
              schema:
                $ref: "#/components/schemas/Review"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      deprecated: false  
      
  /reviews:
    get:
      tags:
      - "reviews"  
      summary: "Get reviews by Status, Customer ID or Product"
      description: "If the user is anonymous, the productId is required. Otherwise, if a valid customer OAUTH authentication exists, then its reviews are listed"
      operationId: "getPendingReviews"
      parameters:
        - in: "query"
          name: "status"
          required: true  
          schema:
            type: string
            default: "pending"
        - in: "query"
          name: "product ID"
          required: false  
          schema:
            type: string
      responses:
        '200':
          description: "Reviews Fetched. If the OAUTH authorizes a customer, returns his or her own reviews with the given parameters. Otherwise, if the OAUTH authorizes a moderator, returns all reviews with the given parameters. "
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Pagination"
            application/xml:
               schema:
                  $ref: "#/components/schemas/Pagination"
          links:
            GetReviewById: 
              operationId: getReview
              parameters:
                reviewId: '$response.body#/reviewId'
                required: true
                description: ""
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      security:
        - OAuth2: [customer_read, moderator]
        
    post:
      tags:
      - "reviews"  
      summary: "Post a new Review"
      description: ""
      operationId: "postReview"
      requestBody:
        required: true
        description: "Data required to post a review (score, reviewDescription)"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Review-Create"
          application/xml:
            schema:
              $ref: "#/components/schemas/Review-Create"
      responses:
        '201':
          description: "Review sent for approval"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  reviewId:
                    type: "string"
                    default: "https://example.org/review/id"
                    description: "Review ID"
            application/xml:
              schema:
                type: "object"
                xml: 
                  name: "review"
                properties:
                  reviewId:
                    type: "integer"
                    format: "int64"
                    description: "Review ID"
          links:
            GetReviewById: 
              operationId: getReview
              parameters:
                reviewId: '$response.body#/reviewId'
                required: true
                description: ""
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"    
      security:
        - OAuth2: [customer_write]
        
components:
  schemas:
    Customer:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        username:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        email:
          type: "string"
        date:
          type: "string"
          format: "date"
        status:
          type: "object"
          format: ""
      xml:
        name: "Customer"
        
    Review:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        funnyFact:
          type: "string"
        score:
          type: "number"
        reviewDescription:
          type: "string"
        date:
          type: "string"
        status:
          type: "string"
          enum:
            - "pending"
            - "accepted"
            - "rejected"
      xml:
        name: "Review"   
        
    Review-Status:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        status:
          type: "string"
          enum:
            - "pending"
            - "accepted"
            - "rejected"
      xml:
        name: "Review" 
        
    Review-Create:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        score:
          type: "number"
        reviewDescription:
          type: "string"
      xml:
        name: "Review" 
        
    Product:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        name:
          type: "string"
        price:
          type: "number"
        description:
          type: "string"
        avgRating:
          type: "number"
        barcode:
          type: "object"
          allOf:
            - $ref: '#/components/schemas/ProductBarcode'
        reviews:
          type: "array"
          items:
            type: "string"
            default: "https://reviews-psidi.herokuapp.com/reviews/:id" 
      xml:
        name: "Product"  
        
    ProductBarcode:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        images:
          type: "array"
          items:
            type: "object"
        sku:
          type: "number"
      xml:
        name: "ProductBarcode"
    
    Pagination:
      type: "object"
      properties:
        previous: 
          type: "string"
        next: 
          type: "string"
        count:
          type: "number"
        listOfURIs:
          type: "array"
          items:
            type: "string"
            default: "https://example.org/example/:id"
      xml:
        name: "Pagination"    

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize #to be changed#
          tokenUrl: https://example.com/oauth/token             #to be changed#
          scopes:
            customer_read: Grants customers read access
            customer_write: Grants customers write access
            moderator: Grants access to moderator operations