openapi: 3.0.0
info:
  description: "Swagger proposed server for the Review Product infrastructure at ACME .Inc"
  version: "0.1"
  title: "ACME Reviews - PSIDI"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "1171071@isep.ipp.pt"
    
servers:
  - url: https://catalog-psidi.herokuapp.com/
    description: Catalog server 
      
tags:
- name: "products"
  description: "Handles the Catalog service requests"

paths:


####### Products #######

  /products:
    get:
      tags:
      - "products"  
      summary: "Returns all of the Products list from the Catalog, where each product includes the description of name and barcode"
      description: ""
      operationId: "getProducts"
      parameters:
        - in: "query"
          name: "Product Name"
          required: false  
          schema:
            type: string
        - in: "query"
          name: "Barcode"
          required: false  
          schema:
            type: string
      responses:
        '200':
          description: "Products Fetched. Returns a Pagination Object, which contains a list with productIds"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Products"
            application/xml:
               schema:
                  $ref: "#/components/schemas/Products"
          links:
            GetProductsById: 
              operationId: getProduct
              parameters:
                productId: '$response.body#/products/productId'
                required: true
                description: ""
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"
      deprecated: false  

  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Get a Product By Id"
      description: "Returns a certain product according to an id that the API user inserts"
      operationId: "getProduct"
      parameters:
        - in: "path"
          name: "productId"
          required: true  
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "Product Obtained"
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Product"
            application/xml:
               schema:
                  $ref: "#/components/schemas/Product"
        "404":
          description: "Not Found"
        "500":
          description: "Internal Server Request"      
        "503":
          description: "Service Unavailable"  
      deprecated: false  
   
components:
  schemas:  

    Product:
      type: "object"
      properties:
        _embedded:
          type: "object"
          readOnly: true
          default: '
          [{"review": 
            { "_links": 
              { "self": 
                { "href":  "http://reviews-psidi.herokuapp.com/v1/reviews?productId={?id}" } 
              }
            }
          },
          
          {"rating": 
            { "_links": 
              [{ "self": 
                { "href":  "http:/catalog-psidi.herokuapp.com/v1/reviews?productId={?id}/rating" } 
              },
              { "productRating": "number" }]
            }
          }]'
        _links:
          type: "object"
          readOnly: true
          default: ' 
            { "self": 
              { "href":  "http://catalog-psidi.herokuapp.com/v1/product/{:id}" } 
            }'
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        name:
          type: "string"
        price:
          type: "number"
        description:
          type: "string"
        avgRating:
          type: "number"
        barcode:
          type: "object"
          allOf:
            - $ref: '#/components/schemas/ProductBarcode'  
        
    Products:
      type: "object"
      properties:
        _embedded:
          type: "object"
          readOnly: true
          default: '
          [{"product": 
            { "_links": 
              [{ "self": 
                { "href":  "/products/1" } 
              },
              { "rating": 
                { "href":  "/products/1/rating" } 
              }]
            }
          },
          {"product": 
            { "_links": 
              [{ "self": 
                { "href":  "/products/2" } 
              },
              { "rating": 
                { "href":  "/products/2/rating" } 
              }]
            }
          }]'
        _links:
          type: "object"
          readOnly: true
          default: ' 
            [{ "self": 
                { "href":  "http://catalog-psidi.herokuapp.com/v1/products" } 
              },
              { "next": 
                { "href":  "http://catalog-psidi.herokuapp.com/v1/products?page=2" } 
              },
              { "previous": 
                { "href":  "http://catalog-psidi.herokuapp.com/v1/products?page=1" } 
              },
              { "start": 
                { "href":  "http://catalog-psidi.herokuapp.com/v1/products?page=1" } 
              },
              { "last": 
                { "href":  "http://catalog-psidi.herokuapp.com/v1/products?page={?lastPage}" } 
              },
              { "find": 
                { "href":  "http://catalog-psidi.herokuapp.com/v1/products/{:id}" } 
              },
              { "items": 
                [{ "href":  "/products/1" },{ "href":  "/products/2" },{ "href":  "/products/3" }] 
              }]'
        totalNumberOfResults:
          type: "integer"
    
    ProductBarcode:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          readOnly: true
        images:
          type: "array"
          items:
            type: "object"
        sku:
          type: "number"
      xml:
        name: "ProductBarcode"
    
Product-Rating:
type: "object"
properties:
          _links:
          type: "object"
          readOnly: true
          default: '
          [
            {"self": 
              { "href": "http://localhost:3000/products/{:Id}/rating"} 
            },
            {"product":
              {"href":"http://product-psidi.herokuapp.com/v1/products/{?id}"}
            },
            {"reviews":
              {"href":"http://reviews-psidi.herokuapp.com/v1/reviews/{?productId}"}
            }
          ]'
        ratingValue:
          type: "integer"
          value: "12"

  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize #to be changed#
          tokenUrl: https://example.com/oauth/token             #to be changed#
          scopes:
            customer_read: Grants customers read access
            customer_write: Grants customers write access
            moderator: Grants access to moderator operations